### ISSUE TITLE
image 和 video 在同一个batch中会报错

### ISSUE THREAD

**Issue by gengenkai** [QwenLM/Qwen3-Omni#93]
### Description

<img width="1299" height="345" alt="Image" src="https://github.com/user-attachments/assets/33c5c22d-591d-4fcf-91a2-cc9299d9eec3" />

<img width="741" height="682" alt="Image" src="https://github.com/user-attachments/assets/f2bdeb24-c2e5-4501-b6e0-80c5151cd4cc" />  image+video在一个batch会报错

### Reproduction

<img width="1299" height="345" alt="Image" src="https://github.com/user-attachments/assets/33c5c22d-591d-4fcf-91a2-cc9299d9eec3" />

<img width="741" height="682" alt="Image" src="https://github.com/user-attachments/assets/f2bdeb24-c2e5-4501-b6e0-80c5151cd4cc" />  image+video在一个batch会报错

### Logs

```shell

```

### Environment Information

 <img width="1299" height="345" alt="Image" src="https://github.com/user-attachments/assets/33c5c22d-591d-4fcf-91a2-cc9299d9eec3" />

<img width="741" height="682" alt="Image" src="https://github.com/user-attachments/assets/f2bdeb24-c2e5-4501-b6e0-80c5151cd4cc" />  image+video在一个batch会报错

### Known Issue

- [ ] The issue hasn't been already addressed in Documentation, Issues, and Discussions.

**Comment by gengenkai** [comment]
安装最新transformers版本又有新的error：
Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'mrope_interleaved', 'mrope_section', 'interleaved'}
Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'mrope_section', 'interleaved'}
Traceback (most recent call last):
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/Qwen3-Omni/test_omni3_novllm.py", line 10, in <module>
    model = Qwen3OmniMoeForConditionalGeneration.from_pretrained(
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/modeling_utils.py", line 270, in _wrapper
    return func(*args, **kwargs)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4451, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/models/qwen3_omni_moe/modeling_qwen3_omni_moe.py", line 3807, in __init__
    self.enable_talker()
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/models/qwen3_omni_moe/modeling_qwen3_omni_moe.py", line 3812, in enable_talker
    self.code2wav = Qwen3OmniMoeCode2Wav._from_config(self.config.code2wav_config)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/modeling_utils.py", line 270, in _wrapper
    return func(*args, **kwargs)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2049, in _from_config
    model = cls(config, **kwargs)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/models/qwen3_omni_moe/modeling_qwen3_omni_moe.py", line 3740, in __init__
    self.pre_transformer = Qwen3OmniMoeCode2WavTransformerModel._from_config(config)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/modeling_utils.py", line 270, in _wrapper
    return func(*args, **kwargs)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2049, in _from_config
    model = cls(config, **kwargs)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/models/qwen3_omni_moe/modeling_qwen3_omni_moe.py", line 3569, in __init__
    self.rotary_emb = Qwen3OmniMoeRotaryEmbedding(config=config)
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/models/qwen3_omni_moe/modeling_qwen3_omni_moe.py", line 2435, in __init__
    self.rope_type = self.config.rope_parameters["rope_type"]
  File "/mnt/tidalfs-bdsz01/usr/xiangyi3/miniconda3/envs/omni1011/lib/python3.10/site-packages/transformers/configuration_utils.py", line 198, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'Qwen3OmniMoeCode2WavConfig' object has no attribute 'rope_parameters'

**Comment by BakerBunker** [comment]
This bug was introduced by https://github.com/huggingface/transformers/pull/39847

**Comment by gengenkai** [comment]
> This bug was introduced by [huggingface/transformers#39847](https://github.com/huggingface/transformers/pull/39847)
那个bug预计什么时候可以修复呢

**Comment by zucchini-nlp** [comment]
@gengenkai I could not reproduce using the demo inference script for the model below. Can you provide a minimal script?

Also btw @BakerBunker, I noticed the tests in transformers were not updated and still use Omni-2.5. I think that is the reason we didn't see issues previously. If you have time, would be nice to update checkpoints and expected outputs, otherwise I will work on it when I'm back from vacation in November 


```python

import torch
from transformers import Qwen3OmniMoeForConditionalGeneration, Qwen3OmniMoeProcessor

model = Qwen3OmniMoeForConditionalGeneration.from_pretrained(
    "Qwen/Qwen3-Omni-30B-A3B-Instruct",
    dtype="auto",
    device_map="auto"
)
processor = Qwen3OmniMoeProcessor.from_pretrained("Qwen/Qwen3-Omni-30B-A3B-Instruct", min_pixels=28*28, max_pixels=56*56)

# Conversation with video only
conversation1 = [
    {
        "role": "system",
        "content": [
            {"type": "text", "text": "You are Qwen, a virtual human developed by the Qwen Team, Alibaba Group, capable of perceiving auditory and visual inputs, as well as generating text and speech."}
        ],
    },
    {
        "role": "user",
        "content": [
            {"type": "video", "path": "/raid/raushan/karate.mp4"},
        ]
    }
]

# Conversation with audio only
conversation2 = [
    {
        "role": "system",
        "content": [
            {"type": "text", "text": "You are Qwen, a virtual human developed by the Qwen Team, Alibaba Group, capable of perceiving auditory and visual inputs, as well as generating text and speech."}
        ],
    },
    {
        "role": "user",
        "content": [
            {"type": "audio", "path": "/raid/raushan/audio.wav"},
        ]
    }
]


conversations = [conversation1, conversation2]

inputs = processor.apply_chat_template(
    conversations,
    load_audio_from_video=False,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
    num_frames=1,

    # kwargs to be passed to `Qwen3OmniMoeProcessor`
    padding=True,
    use_audio_in_video=False,
).to(device=model.thinker.device, dtype=torch.bfloat16)

text_ids = model.generate(**inputs, use_audio_in_video=False, return_audio=False)
text = processor.batch_decode(text_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(text)
```

**Comment by gengenkai** [comment]
> [@gengenkai](https://github.com/gengenkai) I could not reproduce using the demo inference script for the model below. Can you provide a minimal script?
> 
> Also btw [@BakerBunker](https://github.com/BakerBunker), I noticed the tests in transformers were not updated and still use Omni-2.5. I think that is the reason we didn't see issues previously. If you have time, would be nice to update checkpoints and expected outputs, otherwise I will work on it when I'm back from vacation in November
> 
> import torch
> from transformers import Qwen3OmniMoeForConditionalGeneration, Qwen3OmniMoeProcessor
> 
> model = Qwen3OmniMoeForConditionalGeneration.from_pretrained(
>     "Qwen/Qwen3-Omni-30B-A3B-Instruct",
>     dtype="auto",
>     device_map="auto"
> )
> processor = Qwen3OmniMoeProcessor.from_pretrained("Qwen/Qwen3-Omni-30B-A3B-Instruct", min_pixels=28*28, max_pixels=56*56)
> 
> # Conversation with video only
> conversation1 = [
>     {
>         "role": "system",
>         "content": [
>             {"type": "text", "text": "You are Qwen, a virtual human developed by the Qwen Team, Alibaba Group, capable of perceiving auditory and visual inputs, as well as generating text and speech."}
>         ],
>     },
>     {
>         "role": "user",
>         "content": [
>             {"type": "video", "path": "/raid/raushan/karate.mp4"},
>         ]
>     }
> ]
> 
> # Conversation with audio only
> conversation2 = [
>     {
>         "role": "system",
>         "content": [
>             {"type": "text", "text": "You are Qwen, a virtual human developed by the Qwen Team, Alibaba Group, capable of perceiving auditory and visual inputs, as well as generating text and speech."}
>         ],
>     },
>     {
>         "role": "user",
>         "content": [
>             {"type": "audio", "path": "/raid/raushan/audio.wav"},
>         ]
>     }
> ]
> 
> 
> conversations = [conversation1, conversation2]
> 
> inputs = processor.apply_chat_template(
>     conversations,
>     load_audio_from_video=False,
>     add_generation_prompt=True,
>     tokenize=True,
>     return_dict=True,
>     return_tensors="pt",
>     num_frames=1,
> 
>     # kwargs to be passed to `Qwen3OmniMoeProcessor`
>     padding=True,
>     use_audio_in_video=False,
> ).to(device=model.thinker.device, dtype=torch.bfloat16)
> 
> text_ids = model.generate(**inputs, use_audio_in_video=False, return_audio=False)
> text = processor.batch_decode(text_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)
> print(text)

现在我基于最新transformers版本 
transformers                  5.0.0.dev0
transformers-stream-generator 0.0.5
按照demo的方式加载模型会报错：AttributeError: 'Qwen3OmniMoeCode2WavConfig' object has no attribute 'rope_parameters'

**Comment by zucchini-nlp** [comment]
Unfortunately can't help without a clear reproducer, similar to above tiny python scipt

**Comment by gengenkai** [comment]
> Unfortunately can't help without a clear reproducer, similar to above tiny python scipt

[test_omni3_novllm.py](https://github.com/user-attachments/files/23023057/test_omni3_novllm.py)

**Comment by zucchini-nlp** [comment]
Thanks, located the issue and opening a fix in transformers. Weird it didn't reproduce earlier for me with the same model, prob the wrong commit was installed

**Comment by WikiChao** [comment]
I encountered the same issue even with the newest release of transformers:

Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'mrope_section', 'mrope_interleaved', 'interleaved'}
Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'mrope_section', 'interleaved'}

is this problem solved already>?
